# All values in no of frames
BACKGROUND_COLOR: white
FRAME_RATE: 60
TRAINEE_SESSIONS_TRIALS_INT: 36
WAIT_FOR_KEY_S: 4
SHOW_RESULTS_S: 0.4
DIGIT_AFTER_COMA_RESULTS_INT: 2
WAIT_TO_NEXT_TRIALS_S: 0.2
REPEATS_OF_COLOR_IN_TRIALS_INT: 7
HOW_MANY_CONTROLS_INT: 3

FIX_CROSS_TIME: 30
NO_TRAINING_TRIALS: [36, 1]
INTRA_BLOCK_TRAINIG: 2
NO_BLOCKS: 2
TRAINING_CSI: 36
QUE_COLOR: darkred
QUE_RADIUS: 20
QUE_SPEED: 2
QUE_FREQ: 3
QUE_SHIFT: 40
STIM_LETTERS: ←→↑↓
STIM_SIZE: 25
STIM_SHIFT: 600
STIM_TIME: 15
REACTION_TIME: 90
MASK_TIME: 10
REACTION_KEYS: ["d", "f", "j", "k"]
REACTION_KEYS_SEP: 30
CSI_BAND: [13, 18]
STIM_COLOR: dimgray

RED: "ff0000"
GREEN: "90ee90"
BLUE: "6060ff"
PINK: "da4bbb"
PL_RED_NAME: "czerwony"
PL_GREEN_NAME: "zielony"
PL_BLUE_NAME: "niebieski"
PL_PINK_NAME: "różowy"
RUS_RED_NAME: "красный"
RUS_GREEN_NAME: "зеленый"
RUS_BLUE_NAME: "голубо́й"
RUS_PINK_NAME: "ро́зовый"
COLORS_ARRAY_HEX: ["ff0000", "90ee90", "6060ff", "da4bbb"]
ADJECTIVES: ["wysoki", "szeroki", "głęboki", "wypukły"]
COLORS_PL_ARRAY: ["czerwony", "zielony", "niebieski", "różowy"]
COLORS_RUS_ARRAY: ["красный", "зеленый",
                   "\u0433\u043e\u043b\u0443\u0431\u043e\u0439",
                   "\u0440\u043e\u0437\u043e\u0432\u044b\u0439"]
MAPPING: {
            d: "#ff0000",
            f: "#90ee90",
            j: "#6060ff",
            k: "#da4bbb",
}
