# All values in no of frames
BACKGROUND_COLOR: '#acacac'
FRAME_RATE: 60
TRAINEE_SESSIONS_TRIALS_INT: 36
WAIT_FOR_KEY_S: 4
SHOW_RESULTS_S: 0.4
DIGIT_AFTER_COMA_RESULTS_INT: 2
WAIT_TO_NEXT_TRIALS_S: 0.2
REPEATS_OF_COLOR_IN_TRIALS_INT: 7
HOW_MANY_CONTROLS_INT: 23
FIX_CROSS_TIME: 2
FONT_SIZE_INT: 36
FONT_STYLE: "Arial"
FONT_SIZE_STIM_INT: 42
CROSS_SIZE_INT: 50
HINTS_PLACE_X: 0
HINTS_PLACE_Y: 500
REACTION_KEYS: ["d", "f", "j", "k"]
RED: "ff0000"
GREEN: "90ee90"
BLUE: "6060ff"
PINK: "da4bbb"
PL_RED_NAME: "czerwony"
PL_GREEN_NAME: "zielony"
PL_BLUE_NAME: "niebieski"
PL_PINK_NAME: "różowy"
RUS_RED_NAME: "красный"
RUS_GREEN_NAME: "зеленый"
RUS_BLUE_NAME: "голубо́й"
RUS_PINK_NAME: "ро́зовый"
COLORS_ARRAY_HEX: ["ff0000", "90ee90", "6060ff", "da4bbb"]
ADJECTIVES: ["wysoki", "szeroki", "głęboki", "wypukły"]
COLORS_PL_ARRAY: ["czerwony", "zielony", "niebieski", "różowy"]
COLORS_RUS_ARRAY: ["красный", "зеленый",
                   "\u0433\u043e\u043b\u0443\u0431\u043e\u0439",
                   "\u0440\u043e\u0437\u043e\u0432\u044b\u0439"]
MAPPING: {
            d: "#ff0000",
            f: "#90ee90",
            j: "#6060ff",
            k: "#da4bbb",
}
